public class Bill {
    private Order order;
    private Salesperson salesperson;

    public Bill(Order order, Salesperson salesperson) {
        this.order = order;
        this.salesperson = salesperson;
    }

    public double calculateDiscount() {
        if (order.getCustomer() instanceof InStoreCustomer) {
            InStoreCustomer inStoreCustomer = (InStoreCustomer) order.getCustomer();
            return inStoreCustomer.applyDiscount(order.calculateTotalPrice());
        }
        return 0; // No discount for online customers
    }

    public double calculateFinalAmount() {
        return order.calculateTotalPrice() - calculateDiscount();
    }

    public void display() {
    System.out.println("\nOrder Bill:");

    // Fetch customer details from the order
    Customer customer = order.getCustomer();

    if (customer != null) {
        System.out.println("Customer Type: " + customer.getCustomerType());
        System.out.println("Is Online Order: " + order.isOnline());
        System.out.println("Customer Details: " + customer.toString());
    }

    ShoppingCart shoppingCart = order.getShoppingCart();

    if (shoppingCart != null && !shoppingCart.getItems().isEmpty()) {
        System.out.println("-------- Items in the Order --------");
        for (Item item : shoppingCart.getItems()) {
            System.out.println("Item: " + item.getName() +
                    ", Quantity: " + item.getQuantity() +
                    ", Unit Price: $" + item.getUnitPrice() +
                    ", Total Price: $" + item.calculateTotalPrice());
        }
        System.out.println("------------------------------------");
    } else {
        System.out.println("No items in the order.");
    }

    System.out.println("Total Price: $" + order.calculateTotalPrice());
    double discount = calculateDiscount();
    System.out.println("Discount Applied: $" + discount);
    double finalAmount = calculateFinalAmount();
    System.out.println("Final Amount after Discount: $" + finalAmount);

    // Assuming a method to calculate and display reward points
    if (order.getCustomer() instanceof OnlineCustomer) {
        OnlineCustomer onlineCustomer = (OnlineCustomer) order.getCustomer();
        onlineCustomer.displayRewardPoints();
    }

    System.out.println("Bill generated by Salesperson ID: " + salesperson.getId());
}
}
